### ISSUE TITLE
Support for digispark

### ISSUE THREAD

**Issue by AngeloCore** [rwaldron/johnny-five#1812] opened 2023-02-12 16:12 UTC
Can you add support/examples for digispark boards? Eg attiny85

I don't know if this is useful, but:
```
http://digistump.com/package_digistump_index.json
```

**Comment by dtex** [comment] 2023-02-12 17:50
Did some digging, and the problem is that firmata does not run on the atttiny85. That would be the blocker for adding Digispark support. I'll add your request to the [Requeted Features](https://github.com/rwaldron/johnny-five/wiki/Requested-Features) wiki page, but for Digispark support to happen would require work on the firmata side or a whole new IO altogether (Little Wire support maybe?).

So I'm closing this, not because we don't want to support it, but because it will take a very motivated contributor to get it done.

**Closed by dtex** 2023-02-12 17:50 UTC
