### ISSUE TITLE
Servo: Event move:complete 

### ISSUE THREAD

**Issue by goliatone** [rwaldron/johnny-five#727] opened 2015-04-14 00:28 UTC
I just observed that servo **will not** fire events if **time** is not provided:
```js
function handler(){
  console.log('DONE');
}
servo.on('move:complete', handler);
servo.to(20);
```

If you **do specify** a time argument, it does fire the event:
```js
function handler(){
  console.log('DONE');
}
servo.on('move:complete', handler);
servo.to(20, 200);
```

Is this behavior expected? If so, could we mention such detail in the wiki?

**Comment by dtex** [comment] 2015-04-14 01:20
Expected behavior. It's an exclamation on the wiki tonight.

Ha, so much for speech to text... Let's try that again...

That is expected behavior. I'll write up an explanation for the wiki tonight.

**Comment by dtex** [comment] 2015-04-14 02:27
So currently the wiki says:

## Events

It's recommended to use a rotary potentiometer as the mechanism for determining servo movement.

- **move:complete** this is emitted when a timed move is completed.

---------------------------------------

Here's my proposed change:

## Events

It's recommended to use a rotary potentiometer as the mechanism for determining servo movement.

- **move:complete** this is emitted when a timed move is completed. A timed move is any call to Servo.to() or Servo.step() that includes a duration parameter. Calling either of these methods without a duration is not an asynchronous task.

---------------------------------------

Is that better or is it still murky?

**Comment by goliatone** [comment] 2015-04-14 02:50
Yes, I think is better.
I actually had read that paragraph in the documentation, but apparently my
attention got stuck on the potentiometer part and I started thinking how
would that work making me not pay enough attention to the move:complete
part.

**Comment by Traverso** [comment] 2015-04-14 07:50
What about:
move:complete this is emitted when a timed move is completed.
The event won't fire unless a time argument has been passed to the servo.to method

**Comment by Resseguie** [comment] 2015-04-14 17:04
@dtex Could we just fire the event anyway, even for the synchronous task? That makes the event listening code simple and consistent as in the OP example.

**Comment by dtex** [comment] 2015-04-14 18:41
That makes me uncomfortable because the servo will not have actually finished moving when move:complete is fired.

**Comment by rwaldron** [comment] 2015-04-14 18:49
> That makes me uncomfortable because the servo will not have actually finished moving when move:complete is fired.

Agree.

**Comment by Resseguie** [comment] 2015-04-14 18:52
Misunderstood you then. I thought you were saying the whole thing was synchronous (including the servo movement) if no duration given.

I thought that was strange, but it's what your proposed doc update implied to me.

**Comment by dtex** [comment] 2015-04-14 18:54
Well in that case my wording is poor. @Traverso's is simpler and avoids that miscommunication

**Comment by rwaldron** [comment] 2015-04-14 18:55
Unless you explicitly specify the duration, the value angle is written to the servo, and it travels there at default factory speed. There is no way to know how long that takes or when it completed without closing the feedback loop with some kind of sensor. Therefore, it's wrong to emit confirmation of completion when you have no control over the time an operation takes.

**Comment by Resseguie** [comment] 2015-04-14 18:56
> @Traverso's is simpler and avoids that miscommunication

agreed

**Comment by rwaldron** [comment] 2015-05-18 23:34
Is this updated?

**Comment by dtex** [comment] 2015-05-19 01:27
I've updated the wiki

**Closed by dtex** 2015-05-19 01:27 UTC
