### ISSUE TITLE
Quick flick of button fires 'down' event last

### ISSUE THREAD

**Issue by natevw** [rwaldron/johnny-five#152] opened 2013-06-29 17:43 UTC
Using code from the NodeConf 2013 demo:

```
var five = require('johnny-five'), button, led;

five.Board().on('ready', function () {
  button = new five.Button(8);
  led = new five.Led(13);
  button.on('down', function () { led.on(); });
  button.on('up', function () { led.off(); });
});
```

This works ± as expected, but a real quick "flick" of the button usually leaves pin 13 in the high state.

**Comment by dtex** [comment] 2015-01-26 13:21
@natevw did you ever have an opportunity to see if ```isPullup: true``` solved the issue for you? When I wired for isPullup but did not set the property to true it didn't really work at all which is different than your experience. I have not been able to replicate the issue but maybe I'm just too slow on the button? (read: I'm old)

**Comment by natevw** [comment] 2015-02-03 22:34
@dtex It's been ages, but I really doubt the pullup setting is related. This issue isn't about randomly floating values. IIRC, it seemed that I was triggering an "edge case" of sorts that the JS debounce logic didn't account for.

**Comment by rwaldron** [comment] 2015-02-04 14:46
@natevw probably fixed in this patch? https://github.com/rwaldron/johnny-five/commit/2884556d9a06314dd91dad3c889d8edd753a60cf

**Comment by dtex** [comment] 2015-02-04 15:57
That change narrowed the application of the debounce to a single instance of Button. His test case only had one button so I don't think it made a difference here. I went through all the J5 changes and didn't see anything from the time he submitted this issue until now that would have affected this. Could it have been something that was fixed in StandardFirmata or Firmata.js?

**Comment by rwaldron** [comment] 2015-02-04 17:00
Yeah, I remember this now, but I also remember not quite understanding the issue.

**Comment by dtex** [comment] 2015-07-19 04:23
I honestly believe this is no longer an issue (there have been 15 commits to Button() since this was reported). I've repeatedly tried to reproduce, tapping the button like an over-caffeinated chipmunk and no dice. It just keeps working as it should. Given the number of people that did this at JSConf, I feel pretty confident that we can close the issue even though we don't know exactly when/how it was fixed.

Maybe we need a tag for "Proposed closing"? If we add the tag and then nothing happens for thirty days, close it.

**Comment by rwaldron** [comment] 2015-07-19 17:51
@dtex that sounds good to me, go ahead and create it

**Comment by dtex** [comment] 2015-07-20 03:13
Done. we can use this when appropriate, and then occasionally scan the list of issues with this tag. Any that have had the tag for more than 30 days with no additional comments can be closed.

**Closed** 2015-12-08 20:58 UTC
Labels: bug, question, Recommend Closing
